version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phone-catalogue-backend
    ports:
      - "3001:3001"
    env_file:
      ./backend/.env.local
    networks:
      - phone-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phone-catalogue-frontend
    ports:
      - "3000:3000"
    env_file:
      ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - phone-network
    restart: unless-stopped

networks:
  phone-network:
    driver: bridge
